store_version: 150
robots:
  CRAWLER-1600-001:
    water_current_velocity: 1.0
    water_turbidity: 8.0
    obstacle_density: high
    mothership_support: strong
    confidence: 0.9
    overall_status: available
    survival_status: normal
    thruster_status: normal
    depth_keeping_status: normal
    sonar_status: normal
    vision_status: normal
    arm_status: normal
    end_effector_status: normal
    acoustic_comms_status: normal
    tether_connection_status: normal
    version: 0
    updated_at: '2026-04-19T13:55:00+08:00'
  TOWED-1500-001:
    water_current_velocity: 1.0
    water_turbidity: 8.0
    obstacle_density: high
    mothership_support: strong
    confidence: 0.9
    overall_status: available
    survival_status: normal
    thruster_status: normal
    depth_keeping_status: normal
    sonar_status: normal
    vision_status: normal
    arm_status: normal
    end_effector_status: normal
    acoustic_comms_status: normal
    tether_connection_status: normal
    version: 0
    updated_at: '2026-04-19T13:55:00+08:00'
  SPECIAL-600-001:
    water_current_velocity: 1.0
    water_turbidity: 8.0
    obstacle_density: high
    mothership_support: strong
    confidence: 0.9
    overall_status: available
    survival_status: normal
    thruster_status: normal
    depth_keeping_status: normal
    sonar_status: normal
    vision_status: normal
    arm_status: normal
    end_effector_status: normal
    acoustic_comms_status: normal
    tether_connection_status: normal
    version: 0
    updated_at: '2026-04-19T13:55:00+08:00'
  WROV-250-001:
    water_current_velocity: 1.0
    water_turbidity: 8.0
    obstacle_density: high
    mothership_support: strong
    confidence: 0.9
    overall_status: available
    survival_status: normal
    thruster_status: normal
    depth_keeping_status: normal
    sonar_status: normal
    vision_status: normal
    arm_status: normal
    end_effector_status: normal
    acoustic_comms_status: normal
    tether_connection_status: normal
    version: 16
    updated_at: '2026-08-21T10:47:54.934473+08:00'
  LROV-150-001:
    water_current_velocity: 0.1
    water_turbidity: 1.0
    obstacle_density: low
    mothership_support: strong
    confidence: 0.9
    overall_status: available
    survival_status: normal
    thruster_status: normal
    depth_keeping_status: normal
    sonar_status: normal
    vision_status: normal
    arm_status: normal
    end_effector_status: normal
    acoustic_comms_status: normal
    tether_connection_status: normal
    version: 62
    updated_at: '2026-06-30T17:38:00.043508+08:00'
    status: available
    current_velocity: 0.1
    turbidity: 1.0
  LROV-150-002:
    water_current_velocity: 1.0
    water_turbidity: 8.0
    obstacle_density: high
    mothership_support: strong
    confidence: 0.9
    overall_status: available
    survival_status: normal
    thruster_status: normal
    depth_keeping_status: normal
    sonar_status: normal
    vision_status: normal
    arm_status: normal
    end_effector_status: normal
    acoustic_comms_status: normal
    tether_connection_status: normal
    version: 0
    updated_at: '2026-04-19T13:55:00+08:00'
  OBSROV-75-001:
    water_current_velocity: 0.2
    water_turbidity: 3.0
    obstacle_density: low
    mothership_support: strong
    confidence: 0.9
    overall_status: available
    survival_status: normal
    thruster_status: normal
    depth_keeping_status: normal
    sonar_status: normal
    vision_status: normal
    arm_status: normal
    end_effector_status: normal
    acoustic_comms_status: normal
    tether_connection_status: normal
    version: 48
    updated_at: '2026-06-30T17:38:03.076962+08:00'
    current_velocity: 0.2
    turbidity: 3
  AUV-324cc-001:
    water_current_velocity: 1.0
    water_turbidity: 8.0
    obstacle_density: high
    mothership_support: strong
    confidence: 0.9
    overall_status: available
    survival_status: normal
    thruster_status: normal
    depth_keeping_status: normal
    sonar_status: normal
    vision_status: normal
    arm_status: normal
    end_effector_status: normal
    acoustic_comms_status: normal
    tether_connection_status: normal
    version: 0
    updated_at: '2026-04-19T13:55:00+08:00'
